spring.application.name=payment-gateway

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb?TimeZone=Asia/Kolkata
spring.datasource.username=paymentuser
spring.datasource.password=paymentpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

logging.level.com.payment.gateway=DEBUG
logging.level.org.hibernate.SQL=DEBUG
payment.api.key=test-api-key-12345
spring.jpa.open-in-view=false
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.url=/api-docs
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.packagesToScan=com.payment.gateway.controller
springdoc.pathsToMatch=/api/v1/**